### ISSUE TITLE
OTF / TTF versions

### ISSUE THREAD

**Issue by namn** [fcambus/spleen#2]
Hello, do you think a truetype version could be made out of this? Thanks!

**Comment by Vistaus** [comment]
Would love this as well!

**Comment by dunkelstern** [comment]
Started vectorization here: https://github.com/dunkelstern/spleen/tree/feature/ttf-version

Just a start, will work on this over the next days. Upper and lowercase alphabet has been started, but there is optimization potential obviously.

**Comment by dunkelstern** [comment]
TTF-Version currently looks like this in VSCode/Chromium on Ubuntu

![VSCode Screenshot](https://user-images.githubusercontent.com/456385/51402488-ea5e6f80-1b4d-11e9-9e35-ac0e5c990955.png)

As one can see hinting is needed and some glyphs are not unique enough to recognize them (A and R for example are too similar looking).

**Comment by Vistaus** [comment]
@dunkelstern Great job so far! Will keep an eye on your repo :)

**Comment by dunkelstern** [comment]
Done some hinting, this is how it looks on VSCode/Windows now:

![grafik](https://user-images.githubusercontent.com/456385/51433461-cf255a00-1c4a-11e9-88d7-a464b5c50c72.png)

Please try the generated TTF font in the ttf-subdir. Currently supports Latin1 and Powerline characters (untested). Tell me if you want more.

**Comment by Vistaus** [comment]
@dunkelstern Looks amazing! But I can't use it on Linux :( I moved it to /usr/share/fonts, like I do with all fonts, but it doesn't show up in system settings, nor in other apps.

**Comment by dunkelstern** [comment]
I just dropped it in `/home/<user>/.local/share/fonts` and it showed up... weird, perhaps some caching issue? I would try to run `fc-cache -v` as user and root, perhaps it shows up then?

**Comment by Vistaus** [comment]
@dunkelstern Nope, still doesn't show up :/ Using KDE Plasma 5.14 on Solus (Linux). Like I said: other fonts show up fine, so it can't be a configuration issue.

**Comment by namn** [comment]
I converted the BDF to TTF. It is a cheat because the TTF simply embeds the bitmaps. Kinda suit my need at the moment though.

**Comment by josephscade** [comment]
It does not work on my setup: only a-z A-Z letters are printed on the screen

**Comment by dunkelstern** [comment]
> It does not work on my setup: only a-z A-Z letters are printed on the screen

So what's your setup like? I can't help you with anything without knowing anything...

**Comment by josephscade** [comment]
> > It does not work on my setup: only a-z A-Z letters are printed on the screen
> 
> So what's your setup like? I can't help you with anything without knowing anything...

Hello,
I am running Solus OS.
I installed Spleen by downloading the file `ttf/SpleenMedium.ttf` of you pull request. Then I installed it using `gnome-font-viewer`. Then chose it as font in visual Studio Code.
Here is a simple a "Hello, world!" written in C.
The result is similar using other text editors and terminals (tested on `alacritty`, `gedit` and `tilix`).
![spleen-bug](https://user-images.githubusercontent.com/25402018/51855678-1a67f880-232e-11e9-9836-086efcae1e20.png)
Tell me if you want more informations.

**Comment by Vistaus** [comment]
Working fine here on Solus. But I don't use Visual Studio Code.

**Comment by fcambus** [comment]
What would be the intended use case for a TTF or OTF version?

**Comment by namn** [comment]
My current IDE, JetBrains IntelliJ IDEA, does not support bitmap fonts. So right now I cheat, as mentioned above.

**Comment by josephscade** [comment]
@Vistaus What IDE are you using ?

**Comment by dunkelstern** [comment]
@josephscade hm seems you got an older version where only those characters were implemented, please try downloading it from my branch not from the pull request directly.

**Comment by dunkelstern** [comment]
@fcambus @namn Exactly my problem, using PyCharm, VSCode and some other Electron Apps that can only use TTF/OTF not the Bitmap variants

**Comment by fcambus** [comment]
@dunkelstern I appreciate your efforts on this. The TTF file you created looks similar to Spleen 32x64 when opened in a font editor and/or used in this size, but on your screenshots where it is used in smaller sizes, it doesn't. So it means Spleen needs one OTF/TTF file per size, and vectorizing glyphes manually is not going to scale, it also means that each time I modify the BDF files, I also have to modify the .sfd files.

As others have pointed out, OTF/TTF files can be exported in FontForge, but with the caveat that they are embedding bitmaps. This is not optimal either.

I have been working on automatic OTF/TTF generation directly from the BDF files, and it produces vectorized versions for each size. While there are still some issues, I believe the generated files are now ready for wider testing.

OTF files are available for the [8x16](https://www.cambus.net/tmp/spleen-8x16.otf) and [16x32](https://www.cambus.net/tmp/spleen-16x32.otf) versions.

**Comment by dunkelstern** [comment]
Is it ok if I fork and try to develop further it on my own? I would change the name and keep the derivation attribution to spleen and link people back prominently if they want the original pixel fonts.

**Comment by josephscade** [comment]
Thank you for your answer @dunkelstern, you were right!

**Comment by kucharskim** [comment]
Hi @fcambus. I'm using spleen font on my OpenBSD systems, but recently I needed to use Windows and I miss a lot your fonts there. My main use case is console/shell access via PuTTY. You provided in your earlier comments links to OTF working copy of your fonts, but they return HTTP 404 now. Do you have any new version of your fonts?

As I'm not familiar fonts in general, but have question about following your comment:

> As others have pointed out, OTF/TTF files can be exported in FontForge, but with the caveat that they are embedding bitmaps. This is not optimal either.

Why this is not optimal? Your fonts on OpenBSD are bitmap fonts and for console (XTerm in this case) they work like a charm.

**Comment by fcambus** [comment]
@kucharskim: You are in luck, I have in fact been working on this again lately, and wrote my own program to do the conversion from BDF files. It seems to solve some issues that the old OTF files had with some characters.

I have a new version up, created from the 8x16 version: https://www.cambus.net/tmp/spleen.otf

On Windows, it should work correctly if you set size to 12 Pt.

Regarding embedding bitmaps in TTF/OTF files, I don't remember the exact details anymore but IIRC, I'm not sure all font renderer implementations support this feature.

**Comment by kucharskim** [comment]
@fcambus: I've installed 8x16 OTF font from above URL. I can see it in Windows as available font. A side note, in PuTTY spleen font is not visible by default. However when I select `Allow selection of variable-pitch fonts` in PuTTY's `Appearance` settings then I can choose it from the list. I did experiment with different sizes but the font looks nice to me with original size of 8 Pt and that small setting for me is too eye-straining. In XTerm on OpenBSD I use spleen-16x32. Anyway, thanks for working on this and if you need help testing this on Windows, I'm happy to help. Because of small size of the current font version, for now I'm going to stick to different font for everyday work. Cheers.

**Comment by kucharskim** [comment]
@fcambus, small details to clarify, why I've seen 8 Pt as visually most appealing. I had in Windows 10 `Display settings` > `Scale and layout` size set to `150%`. Changing it to `100%` indeed makes Spleen looks best with 12 Pt setting. With desktop scale set to `100%` and Spleen set to 12 Pt it's actually good for my eyes that I can stick to in PuTTY.

**Comment by fcambus** [comment]
@kucharskim Thanks for the update, that's one less thing to investigate then :-) I released 1.6.0 earlier this month with an OTF version created from the 8x16 version. I will see in the future about eventually providing OTF versions for other sizes as well.

**Comment by fcambus** [comment]
So, here is an update.

I have made the initial version of my [bdftosfd](https://github.com/fcambus/bdftosfd) tool public.

It allows me to generate OTF files automatically from the BDF files, and here are some generated fonts available for testing:

- [Spleen 8x16](https://www.cambus.net/tmp/spleen-8x16.otf) (Set size to 12 Pt (16 pixels))
- [Spleen 16x32](https://www.cambus.net/tmp/spleen-16x32.otf) (Set size to 24 Pt (32 pixels))
- [Spleen 32x64](https://www.cambus.net/tmp/spleen-32x64.otf) (Set size to 48 Pt (64 pixels))

If there are no major issues, those fonts will be part of the next Spleen release.

**Comment by namn** [comment]
Thank you for the work, Frederic!

**Comment by fcambus** [comment]
So it's been two weeks and I haven't heard of any issues with the OTF fonts, so I also generated a 12x24 version, and released [Spleen 1.7.0](https://github.com/fcambus/spleen/releases/tag/1.7.0) which has pregenerated versions in the release tarball.

Thanks to everyone who tested the experimental fonts.

**Comment by grolongo** [comment]
Not trying to resuscitate that issue but doesn't converting your bitmap font to an OTF format defeat the main purpose of having a fast displaying font for your console/terminal? Or am I missing something?
